### ISSUE TITLE
Can create extra page when printing 

### ISSUE THREAD

**Issue by p3ppo** [nimeshnayaju/fishtail#1]
Thank you for a great extension, really like it. Perfect for doing demos.

I've discovered that since it adds a div at the bottom of the page, it can create an extra blank page when printing, in some cases. Especially when using https://github.com/cognitom/paper-css. So maybe you can you add print css, so it's hidden when printing, in some future update?

In the meantime I solved the problem by adding a global css with stylebot chrome extension:

```css
/* Fishtail chrome extension print fix */
@media print{
  #fishtail-root {
    display: none;
  }
}
```
